from snakemake.io import expand, touch
from snakemake.utils import validate
from glob import glob
import os
import pandas as pd


###### Config file, environment and sample sheet #####

configfile: "../config/config.yaml"

validate(config, "resources/schemas/config_schema.yaml")

os.environ["SNAKEMAKE_OUTPUT_CACHE"] = f"{os.getcwd()}/resources/vep/cache"

##### Target rules #####

samples_df = pd.read_csv(config["samplesheet"])

samples = samples_df.set_index("sample_id", drop=False)

validate(samples, "resources/schemas/samplesheet_schema.yaml")


sample_study_pairs = list(zip(samples_df["study"], samples_df["sample_id"]))

print("Sample-Study pairs:", sample_study_pairs)


# Check files exist
missing_files = samples_df[~samples_df["mutations"].apply(os.path.exists) | 
                          ~samples_df["cnvs"].apply(os.path.exists)]
if not missing_files.empty:
    raise FileNotFoundError(f"Missing input files in the samplesheet:\n{missing_files}")

rule all:
    input:
        expand("results/{study}/mutation_prep/{sample}_prep.mut.tsv", zip, study=samples_df["study"], sample=samples_df["sample_id"]),
        expand("results/{study}/pyclone-vi_prep/{sample}_intersect_pvi.tsv", zip, study=samples_df["study"], sample=samples_df["sample_id"]),
        expand("results/{study}/pyclone-vi_prep/combined_intersect_pvi.tsv", study=samples_df["study"].unique()),
        expand("results/{study}/pyclone-vi/pvi_out.tsv", study=samples_df["study"].unique()),
        expand("results/{study}/pvi_vep_prep", study=samples_df["study"].unique()),
        "resources/vep/cache",
        expand("results/{study}/vep_annotation/annotations", study=samples_df["study"].unique()),
        expand("results/{study}/query_pandrugs", study=samples_df["study"].unique()),
        expand("results/{study}/phyclone/tree.nwk", study=samples_df["study"].unique()),
        expand("results/{study}/report/components/report_panel.tsv", study=samples_df["study"].unique()),
        expand("results/{study}/report/components/clonal_tree.png", study=samples_df["study"].unique()),
        expand("results/{study}/report/components/spheres_of_clones", study=samples_df["study"].unique()),
        expand("results/{study}/report/components/vaf_heatmaps", study=samples_df["study"].unique()),
        expand("results/{study}/report/components/gene_alterations.tsv", study=samples_df["study"].unique()),
        expand("results/{study}/report/{study}_report.pdf", study=samples_df["study"].unique())


# FORMAT MUTATION VCF

include: "rules/mutation_prep.smk"


# INTERSECT MUTATIONS AND CNVs

include: "rules/pyclone-vi_prep.smk"


# RUN PYCLONE-VI CLONAL INFERENCE

include: "rules/pyclone-vi.smk"


# FORMAT PYCLONE-VI OUTPUT FOR ENSEMBL-VEP

include: "rules/pvi_vep_prep.smk"


# DOWNLOAD ENSEMBL-VEP CACHE

include: "rules/get_vep_cache.smk"


# VEP ANNOTATION PER CLUSTER

include: "rules/vep_annotation.smk"


# QUERY PANDRUGS SMALL VARIANTS

include: "rules/query_pandrugs.smk"


# BUILD SUBCLONAL TREE

include: "rules/phyclone.smk"


# GENERATE REPORT COMPONENTS: PLOTS AND TABLES

include: "rules/report_components.smk"


# RENDER STUDY REPORT TO PDF

include: "rules/render_report.smk"
