samples:
    patient_01:
        id: ""   
        alterations:
            - mutations: ""
            - cna: ""
    patient_02:
        id: ""   
        alterations:
            - mutations: ""
            - cna: ""


params:
    pyclone-vi:
        num-clusters: 40
        density: "beta-binomial"
        num-grid-points: 100
        num-restarts: 10
        seed: 570655569



resources:
    default:
        threads: 1
        mem: 4000
        walltime: 480
    pyclone-vi:
        threads: 2
        mem: 4000
        walltime: 480
    pandrugs:
        threads: 2
        mem: 4000
        walltime: 480
    citup:
        threads: 2
        mem: 4000
        walltime: 480
